#!/usr/bin/env python3
"""Write a PROVENANCE stamp into every report directory.

Three times in three codebases, by three people, this project has committed a report whose
numbers its own code no longer produced -- and in every case the defect was not that the report
was old but that it did not SAY it was old. Recomputation does not fix that; a stamp does.

    python scripts/stamp_reports.py            # write reports/<name>/PROVENANCE.md
    python scripts/stamp_reports.py --check     # exit 1 if any stamp is missing or stale

The stamp is generated, not written by hand, so it cannot drift from the repository. Each one
carries:

  * the commit the report was last written at, and its date;
  * every committed input directory the report reads, and the commit each was last written at;
  * a one-line STATUS -- CURRENT, HISTORICAL or UNKNOWN.

STATUS is NOT guessed from dates. It comes from `reports/report_status.yaml`, where each
report's status is recorded with the evidence for it (usually a prior audit), because whether a
report reproduces is a claim that has to be tested, not inferred. A report with no entry is
stamped UNKNOWN, which is honest and visible.

**HISTORICAL is not a criticism.** Most of these directories are working logs of a night's
work; a log is supposed to describe the state it was written in. The stamp says which state.
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
REPORTS = os.path.join(ROOT, "reports")
STATUS_FILE = os.path.join(REPORTS, "report_status.yaml")
STAMP = "PROVENANCE.md"
MARK = "<!-- generated by scripts/stamp_reports.py -- do not edit by hand -->"
SCAN_EXT = (".py", ".qmd", ".md", ".sh")
OUTPUT_RE = re.compile(r"(strains/[A-Za-z0-9_.-]+/outputs/[A-Za-z0-9_.-]+)")


def git(*args, default=""):
    r = subprocess.run(["git", "-C", ROOT, *args], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else default


def last_commit(path, exclude=None):
    """(short sha, date, subject) of the commit that last wrote `path`, or None if untracked.

    ``exclude`` drops a pathspec from the search. A report's own stamp lives inside the report
    directory, so without excluding it the stamp would record the commit that wrote the stamp --
    self-referential, and ``--check`` would fail immediately after every commit.
    """
    spec = [path] + ([f":(exclude){exclude}"] if exclude else [])
    out = git("log", "-1", "--format=%h|%ad|%s", "--date=short", "--", *spec)
    if not out:
        return None
    h, d, s = out.split("|", 2)
    return h, d, s


def inputs_of(report_dir):
    """Committed strain-output directories this report reads, found by scanning its own files."""
    found = set()
    for base, _dirs, files in os.walk(report_dir):
        if os.sep + "assets" in base:
            continue
        for f in files:
            if not f.endswith(SCAN_EXT):
                continue
            try:
                text = open(os.path.join(base, f), encoding="utf-8", errors="ignore").read()
            except OSError:
                continue
            for m in OUTPUT_RE.findall(text):
                if os.path.isdir(os.path.join(ROOT, m)) and git("ls-files", m):
                    found.add(m)
    return sorted(found)


def load_status():
    if not os.path.exists(STATUS_FILE):
        return {}
    import yaml
    return yaml.safe_load(open(STATUS_FILE)) or {}


def stamp_text(name, report_dir, status_entry):
    entry = status_entry or {}
    rel = os.path.relpath(report_dir, ROOT)
    rc = last_commit(rel, exclude=f"{rel}/{STAMP}")
    lines = [MARK, "", f"# Provenance — `reports/{name}/`", ""]
    status = (status_entry or {}).get("status", "UNKNOWN")
    note = (status_entry or {}).get("note", "no entry in reports/report_status.yaml; status "
                                            "has not been established")
    evidence = (status_entry or {}).get("evidence")
    lines += [f"**STATUS: {status}** — {note}", ""]
    if evidence:
        lines += [f"*Evidence:* {evidence}", ""]
    if rc:
        lines += [f"**This report was last written at** `{rc[0]}` ({rc[1]}) — {rc[2]}", ""]
    else:
        lines += ["**This report is not yet committed.**", ""]
    # A curated `inputs:` list wins over the scan. The scan reads paths out of the report's own
    # files, which misses anything built by string join (reports/ecoli_tpc/assemble.py does this
    # for all eleven of its directories) and picks up directories merely NAMED in prose. Where an
    # audit has established the true list, that list is authoritative.
    curated = entry.get("inputs")
    ins = list(curated) if curated else inputs_of(report_dir)
    src = "from `reports/report_status.yaml`" if curated else "found by scanning this report's own files"
    if ins:
        lines += [f"**Committed inputs it reads ({src}), and the commit each was last written at:**", "",
                  "| input directory | last written | date | commit subject |",
                  "|---|---|---|---|"]
        for p in ins:
            c = last_commit(p)
            if c:
                lines.append(f"| `{p}` | `{c[0]}` | {c[1]} | {c[2][:70]} |")
            else:
                lines.append(f"| `{p}` | *(untracked)* | — | — |")
        lines.append("")
    else:
        lines += ["**Reads no committed strain-output directory** (self-contained, or its "
                  "inputs are its own files).", ""]
    lines += ["---", "",
              "*What the statuses mean.* **CURRENT** — the numbers reproduce from the code as "
              "it stands. **HISTORICAL** — a record of an earlier model state; that is what a "
              "working log is, and it is not a defect. **UNKNOWN** — not established either "
              "way. Regenerate this file with `python scripts/stamp_reports.py`; the statuses "
              "themselves live in `reports/report_status.yaml` with their evidence.", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any stamp is missing or out of date; write nothing")
    args = ap.parse_args()
    statuses = load_status()
    stale, written = [], []
    for name in sorted(os.listdir(REPORTS)):
        d = os.path.join(REPORTS, name)
        if not os.path.isdir(d):
            continue
        text = stamp_text(name, d, statuses.get(name))
        p = os.path.join(d, STAMP)
        old = open(p, encoding="utf-8").read() if os.path.exists(p) else None
        if old == text:
            continue
        if args.check:
            stale.append(name)
        else:
            open(p, "w", encoding="utf-8").write(text)
            written.append(name)
    if args.check:
        if stale:
            print("stamps missing or stale: " + ", ".join(stale))
            print("run: python scripts/stamp_reports.py")
            return 1
        print("every report stamp is up to date")
        return 0
    print(f"wrote {len(written)} stamp(s)" + (": " + ", ".join(written) if written else ""))
    missing = [n for n in sorted(os.listdir(REPORTS))
               if os.path.isdir(os.path.join(REPORTS, n)) and n not in statuses]
    if missing:
        print("  no status recorded (stamped UNKNOWN): " + ", ".join(missing))
    return 0


if __name__ == "__main__":
    sys.exit(main())
